[profile.default]
src = 'src'
out = 'out'
libs = ['lib']

# Compiler configuration
solc = '0.8.30'
optimizer = true
optimizer_runs = 200

# Test configuration
fuzz_runs = 256
ffi = true

# Deployment configuration
[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }

# Solidity remappings
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@1inch/=lib/cross-chain-swap/",
    "@solmate/=lib/solmate/",
    "@openzeppelin-upgradeable/=lib/openzeppelin-contracts-upgradeable/"
]
